services:
  # Main MongoDB for development/testing
  mongo:
    image: mongo:7.0
    container_name: cybercore-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=cybercore_test
    volumes:
      - mongo_data:/data/db
    networks:
      - cybercore-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Main Redis for development/testing
  redis:
    image: redis:7.2-alpine
    container_name: cybercore-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - cybercore-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:
  redis_data:

networks:
  cybercore-network:
    driver: bridge